### ISSUE TITLE
virginphoto.com

### ISSUE THREAD

**Issue by spirillen** [Clefspeare13/pornhosts#129]
I believe this specific domain(s) is to be moved from the hosts file as it no longer is active for Adult material

# Delete this
```
m.virginphoto.com
www.virginphoto.com
```

# Keep this
```

```

## Screenshots

<details><Summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/44526987/88429717-6565ad80-cdf7-11ea-8767-703ea3fe56c0.png)

</details>

## External Info

- https://github.com/Import-External-Sources/pornhosts/issues/617#issuecomment-663704605

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [X] Added ScreenDump for prove of False Positive

### Todo
- [ ] Removed this from [Source file](submit_here/hosts.txt)?
- [X] Removed from the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/wiki/RpzList#adult.mypdns.cloud) (@spirillen)
