### ISSUE TITLE
elblogdelnarco.com

### ISSUE THREAD

**Issue by spirillen** [Clefspeare13/pornhosts#140]
I believe this specific domain(s) is to be moved from the hosts file as it no longer is active for Adult material

# Delete this
```
elblogdelnarco.com
www.elblogdelnarco.com
```

# Keep this 
```

```

## Screenshots

<details><Summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/44526987/89280524-0569d500-d649-11ea-8afc-40404f5c1551.png)

</details>

### All Submissions:
- [x] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added ScreenDump for prove of False Positive

### Todo
- [ ] Removed this from [Source file](submit_here/hosts.txt)?
- [ ] Removed from the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/wiki/RpzList#adult.mypdns.cloud) (@spirillen)

**Comment by spirillen** [comment]
Ping @DaniV5 Could you please take a look at this site? it seems more like your native language than mine :smiley:

**Comment by DaniV5** [comment]
looks like one of those "news" websites with unbelievable titles

**Comment by spirillen** [comment]
Super @DaniV5 Thanks for your quick reply and response.

I believe I dare to remove this one from the list then.
