### ISSUE TITLE
i-am-bored.com

### ISSUE THREAD

**Issue by spirillen** [Clefspeare13/pornhosts#141]
I believe this specific domain(s) is to be moved from the hosts file as it no longer is active for Adult material

# Delete this
```
i-am-bored.com
m.i-am-bored.com
```

# Keep this
```

```

## Details
```
drill -T i-am-bored.com
.       518400  IN      NS      j.root-servers.net.
com.    172800  IN      NS      e.gtld-servers.net.
i-am-bored.com. 172800  IN      NS      ns67.domaincontrol.com.
i-am-bored.com. 172800  IN      NS      ns68.domaincontrol.com.
i-am-bored.com. 600     IN      A       34.98.99.30
i-am-bored.com. 3600    IN      NS      ns67.domaincontrol.com.
i-am-bored.com. 3600    IN      NS      ns68.domaincontrol.com.
```

`domaincontrol.com` are domain pirates <https://www.mypdns.org/T657> (<https://www.mypdns.org/search/query/7xDrNMjlkSZK/#R>), which means this domain is no longer active for porn.

## External Info

- https://www.mypdns.org/search/query/7xDrNMjlkSZK/#R
- https://www.mypdns.org/T657

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [ ] Added ScreenDump for prove of False Positive

### Todo
- [ ] Removed this from [Source file](submit_here/hosts.txt)?
- [x] Removed from the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/wiki/RpzList#adult.mypdns.cloud) (@spirillen)
