### ISSUE TITLE
vrshemaletube.com

### ISSUE THREAD

**Issue by spirillen** [Clefspeare13/pornhosts#142]
I believe this specific domain(s) is to be moved from the hosts file as it no longer is active for Adult material

# Delete this
```
vrshemaletube.com
m.vrshemaletube.com
www.vrshemaletube.com
```

# Details
```shell
drill -T m.vrshemaletube.com
.       518400  IN      NS      a.root-servers.net.
....
com.    172800  IN      NS      c.gtld-servers.net.
com.    900     IN      SOA     a.gtld-servers.net. nstld.verisign-grs.com. 1596793661 1800 900 604800 86400
```

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [ ] Added ScreenDump for prove of False Positive

### Todo
- [ ] Removed this from [Source file](submit_here/hosts.txt)?
- [x] Removed from the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/wiki/RpzList#adult.mypdns.cloud) (@spirillen)
