### ISSUE TITLE
linkarena.com

### ISSUE THREAD

**Issue by spirillen** [Clefspeare13/pornhosts#143]
I believe this specific domain(s) is to be moved from the hosts file as it no longer is active for Adult material

# Delete this
```
angel4u.linkarena.com
m.angel4u.linkarena.com
```

`m.angel4u.linkarena.com`   Redirects to `https://linkarena.com/`

Also I don't find any adult nor porn related contents on `angel4u.linkarena.com`

# Keep this
```

```

```shell
curl -I 'm.angel4u.linkarena.com'
HTTP/1.1 301 Moved Permanently
Date: Fri, 07 Aug 2020 10:12:35 GMT
Server: Apache/2.4.25 (Debian)
X-Powered-By: PHP/5.2.17
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: PHPSESSID=02ef9aa72ebda994c84fc72552369799; path=/; domain=.linkarena.com
Location: http://linkarena.com/
Content-Type: text/html; charset=UTF-8
```

```shell
url -I 'angel4u.linkarena.com'
HTTP/1.1 200 OK
Date: Fri, 07 Aug 2020 10:13:40 GMT
Server: Apache/2.4.25 (Debian)
X-Powered-By: PHP/5.2.17
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: PHPSESSID=a4cb1b6af6e1ae7b2621f5a2a281920e; path=/; domain=.linkarena.com
Content-Type: text/html; charset=UTF-8
```

## Screenshots

<details><Summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/44526987/89636073-56c3cf80-d8a8-11ea-94a1-2a8b1e9d342f.png)

![image](https://user-images.githubusercontent.com/44526987/89636141-6cd19000-d8a8-11ea-951f-b14ab023cc8e.png)

</details>

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [X] Added ScreenDump for prove of False Positive

### Todo
- [ ] Removed this from [Source file](submit_here/hosts.txt)?
- [x] Removed from the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/wiki/RpzList#adult.mypdns.cloud) (@spirillen)
