### ISSUE TITLE
pixhost.to

### ISSUE THREAD

**Issue by spirillen** [Clefspeare13/pornhosts#190]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
pixhost.to
```

Example url for strict contents filtering `https://pixhost.to/show/496/158595707_001-4.jpg`

## Content sources

(Please see #35)

```python
t44.pixhost.to

```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/90313341-071a7f00-df0c-11ea-9e9b-2ce59f971c3f.png)

</details>

## Logger output
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +382 |  |  | pixhost.to | 1 | image | `https://pixhost.to/favicon.ico` |
| +382 | ##button[title="Share"] |  | pixhost.to |  | dom | `https://pixhost.to/show/496/158595707_001-4.jpg` |
| +382 | ##.under-image |  | pixhost.to |  | dom | `https://pixhost.to/show/496/158595707_001-4.jpg` |
| +382 | ##.pswp__button--share |  | pixhost.to |  | dom | `https://pixhost.to/show/496/158595707_001-4.jpg` |
| +382 |  |  | pixhost.to | 3 | font | `https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/fonts/fontawesome-webfont.woff2?v=4.4.0` |
| +382 | google-analytics.com/analytics.js | << | pixhost.to |  | script | `https://www.google-analytics.com/analytics.js` |
| +382 | \|\|google-analytics.com^ | -- | pixhost.to | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +382 | \|\|exdynsrv.com^$3p | -- | pixhost.to | 3 | script | `https://a.exdynsrv.com/ads.js` |
| +382 | \|\|exdynsrv.com^$3p | -- | pixhost.to | 3 | script | `https://a.exdynsrv.com/ads.js` |
| +382 | \|\|exdynsrv.com^$3p | -- | pixhost.to | 3 | script | `https://a.exdynsrv.com/ads.js` |
| +382 | \|\|exdynsrv.com^$3p | -- | pixhost.to | 3 | script | `https://a.exdynsrv.com/ads.js` |
| +382 | \|\|exdynsrv.com^$3p | -- | pixhost.to | 3 | script | `https://a.exdynsrv.com/popunder1000.js` |
| +382 |  |  | pixhost.to | 1 | css | `https://pixhost.to/PhotoSwipe/default-skin/default-skin.css` |
| +382 |  |  | pixhost.to | 1 | css | `https://pixhost.to/PhotoSwipe/photoswipe.css` |
| +382 |  |  | pixhost.to | 1 | css | `https://pixhost.to/css/vendor/primer-tooltips.css?1522185737` |
| +382 |  |  | pixhost.to | 3 | css | `https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css` |
| +382 | @@\|\|pixhost.to/photoswipe/photoswipe-*.js | ++ | pixhost.to | 1 | script | `https://pixhost.to/PhotoSwipe/photoswipe-ui-default.min.js` |
| +382 | @@\|\|pixhost.to/photoswipe/photoswipe.*.js | ++ | pixhost.to | 1 | script | `https://pixhost.to/PhotoSwipe/photoswipe.min.js` |
| +382 | @@\|\|pixhost.to/js/image.js? | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/image.js?1522185737` |
| +382 | @@\|\|pixhost.to/js/vendor/jquery.*.js | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/vendor/jquery.touchSwipe.min.js` |
| +382 | @@\|\|pixhost.to/js/clipboard-helpers.js? | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/clipboard-helpers.js?1522185737` |
| +382 | @@\|\|pixhost.to/js/vendor/clipboard.min.js? | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/vendor/clipboard.min.js?1522185737` |
| +382 | @@\|\|pixhost.to/lang.js.php? | ++ | pixhost.to | 1 | script | `https://pixhost.to/lang.js.php?l=en&1522185737` |
| +382 | @@\|\|pixhost.to/js/helpers.js? | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/helpers.js?1522185737` |
| +382 | @@\|\|pixhost.to/js/main.js? | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/main.js?1522185737` |
| +382 |  |  | pixhost.to | 1 | image | `https://pixhost.to/image/flags/en.png` |
| +382 |  |  | pixhost.to | 1 | image | `https://pixhost.to/image/flags/ru.png` |
| +382 |  |  | pixhost.to | 1 | image | `https://pixhost.to/image/flags/de.png` |
| +382 |  |  | pixhost.to | 1 | image | `https://pixhost.to/image/flags/cz.png` |
| +382 |  |  | pixhost.to | 1 | image | `https://pixhost.to/image/flags/sk.png` |
| +382 |  |  | pixhost.to | 1 | image | `https://img44.pixhost.to/images/496/158595707_001-4.jpg` |
| +382 | \|\|exdynsrv.com^$3p | -- | pixhost.to | 3 | script | `https://a.exdynsrv.com/ads.js` |
| +382 |  |  | pixhost.to | 1 | image | `https://pixhost.to/image/logo_min.png?1522185737` |
| +382 | @@\|\|pixhost.to/js/vendor/jquery.*.js | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/vendor/jquery.cookie.js?1522185737` |
| +382 | @@\|\|pixhost.to/js/vendor/jquery-*.js? | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/vendor/jquery-1.11.1.min.js?1522185737` |
| +382 |  |  | pixhost.to | 1 | css | `https://pixhost.to/css/main.css?1522185737` |
| +382 | ##+js(abort-on-property-write, readyADN) |  | pixhost.to |  | dom | `https://pixhost.to/show/496/158595707_001-4.jpg` |
| +382 | ##+js(abort-on-property-read, ShowIt) |  | pixhost.to |  | dom | `https://pixhost.to/show/496/158595707_001-4.jpg` |
| +382 | ##+js(abort-on-property-read, ExoDetector) |  | pixhost.to |  | dom | `https://pixhost.to/show/496/158595707_001-4.jpg` |
| +381 |  |  | pixhost.to | 1 | doc | `https://pixhost.to/show/496/158595707_001-4.jpg` |
| +60 | \|\|exdynsrv.com^$3p | -- | pixhost.to | 3 | frame | `https://syndication.exdynsrv.com/ads-iframe-display.php?idzone=3659907&output=noscript&type=900x250` |
| +60 |  |  | pixhost.to | 1 | image | `https://pixhost.to/favicon.ico` |
| +60 | ##button[title="Share"] |  | pixhost.to |  | dom | `https://pixhost.to/show/497/158604220_001-13.jpg` |
| +60 | ##.under-image |  | pixhost.to |  | dom | `https://pixhost.to/show/497/158604220_001-13.jpg` |
| +60 | ##.pswp__button--share |  | pixhost.to |  | dom | `https://pixhost.to/show/497/158604220_001-13.jpg` |
| +60 | google-analytics.com/analytics.js | << | pixhost.to |  | script | `https://www.google-analytics.com/analytics.js` |
| +60 | \|\|google-analytics.com^ | -- | pixhost.to | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +60 | \|\|exdynsrv.com^$3p | -- | pixhost.to | 3 | script | `https://a.exdynsrv.com/ads.js` |
| +60 | \|\|exdynsrv.com^$3p | -- | pixhost.to | 3 | script | `https://a.exdynsrv.com/ads.js` |
| +60 | \|\|exdynsrv.com^$3p | -- | pixhost.to | 3 | script | `https://a.exdynsrv.com/ads.js` |
| +60 | \|\|exdynsrv.com^$3p | -- | pixhost.to | 3 | script | `https://a.exdynsrv.com/popunder1000.js` |
| +60 | @@\|\|pixhost.to/photoswipe/photoswipe-*.js | ++ | pixhost.to | 1 | script | `https://pixhost.to/PhotoSwipe/photoswipe-ui-default.min.js` |
| +60 | @@\|\|pixhost.to/photoswipe/photoswipe.*.js | ++ | pixhost.to | 1 | script | `https://pixhost.to/PhotoSwipe/photoswipe.min.js` |
| +60 | @@\|\|pixhost.to/js/image.js? | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/image.js?1522185737` |
| +60 | @@\|\|pixhost.to/js/vendor/jquery.*.js | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/vendor/jquery.touchSwipe.min.js` |
| +60 | @@\|\|pixhost.to/js/clipboard-helpers.js? | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/clipboard-helpers.js?1522185737` |
| +60 | @@\|\|pixhost.to/js/vendor/clipboard.min.js? | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/vendor/clipboard.min.js?1522185737` |
| +60 | @@\|\|pixhost.to/lang.js.php? | ++ | pixhost.to | 1 | script | `https://pixhost.to/lang.js.php?l=en&1522185737` |
| +60 | @@\|\|pixhost.to/js/helpers.js? | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/helpers.js?1522185737` |
| +60 | @@\|\|pixhost.to/js/main.js? | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/main.js?1522185737` |
| +60 |  |  | pixhost.to | 1 | image | `https://img44.pixhost.to/images/497/158604220_001-13.jpg` |
| +60 | \|\|exdynsrv.com^$3p | -- | pixhost.to | 3 | script | `https://a.exdynsrv.com/ads.js` |
| +60 | @@\|\|pixhost.to/js/vendor/jquery.*.js | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/vendor/jquery.cookie.js?1522185737` |
| +60 | @@\|\|pixhost.to/js/vendor/jquery-*.js? | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/vendor/jquery-1.11.1.min.js?1522185737` |
| +60 | ##+js(abort-on-property-write, readyADN) |  | pixhost.to |  | dom | `https://pixhost.to/show/497/158604220_001-13.jpg` |
| +60 | ##+js(abort-on-property-read, ShowIt) |  | pixhost.to |  | dom | `https://pixhost.to/show/497/158604220_001-13.jpg` |
| +60 | ##+js(abort-on-property-read, ExoDetector) |  | pixhost.to |  | dom | `https://pixhost.to/show/497/158604220_001-13.jpg` |
| +59 |  |  | pixhost.to | 1 | doc | `https://pixhost.to/show/497/158604220_001-13.jpg` |
| +47 |  |  | pixhost.to | 1 | image | `https://pixhost.to/favicon.ico` |
| +47 | ##.pswp__button--share |  | pixhost.to |  | dom | `https://pixhost.to/show/497/158604212_001-7.jpg` |
| +47 | ##button[title="Share"] |  | pixhost.to |  | dom | `https://pixhost.to/show/497/158604212_001-7.jpg` |
| +47 | ##.under-image |  | pixhost.to |  | dom | `https://pixhost.to/show/497/158604212_001-7.jpg` |
| +47 |  |  | pixhost.to | 3 | font | `https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/fonts/fontawesome-webfont.woff2?v=4.4.0` |
| +47 | google-analytics.com/analytics.js | << | pixhost.to |  | script | `https://www.google-analytics.com/analytics.js` |
| +47 | \|\|google-analytics.com^ | -- | pixhost.to | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +46 | \|\|exdynsrv.com^$3p | -- | pixhost.to | 3 | script | `https://a.exdynsrv.com/ads.js` |
| +46 | \|\|exdynsrv.com^$3p | -- | pixhost.to | 3 | script | `https://a.exdynsrv.com/ads.js` |
| +46 | \|\|exdynsrv.com^$3p | -- | pixhost.to | 3 | script | `https://a.exdynsrv.com/ads.js` |
| +46 | \|\|exdynsrv.com^$3p | -- | pixhost.to | 3 | script | `https://a.exdynsrv.com/ads.js` |
| +46 | \|\|exdynsrv.com^$3p | -- | pixhost.to | 3 | script | `https://a.exdynsrv.com/popunder1000.js` |
| +46 |  |  | pixhost.to | 1 | css | `https://pixhost.to/PhotoSwipe/default-skin/default-skin.css` |
| +46 |  |  | pixhost.to | 1 | css | `https://pixhost.to/PhotoSwipe/photoswipe.css` |
| +46 |  |  | pixhost.to | 1 | css | `https://pixhost.to/css/vendor/primer-tooltips.css?1522185737` |
| +46 |  |  | pixhost.to | 3 | css | `https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css` |
| +46 | @@\|\|pixhost.to/photoswipe/photoswipe-*.js | ++ | pixhost.to | 1 | script | `https://pixhost.to/PhotoSwipe/photoswipe-ui-default.min.js` |
| +46 | @@\|\|pixhost.to/photoswipe/photoswipe.*.js | ++ | pixhost.to | 1 | script | `https://pixhost.to/PhotoSwipe/photoswipe.min.js` |
| +46 | @@\|\|pixhost.to/js/image.js? | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/image.js?1522185737` |
| +46 | @@\|\|pixhost.to/js/vendor/jquery.*.js | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/vendor/jquery.touchSwipe.min.js` |
| +46 | @@\|\|pixhost.to/js/clipboard-helpers.js? | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/clipboard-helpers.js?1522185737` |
| +46 | @@\|\|pixhost.to/js/vendor/clipboard.min.js? | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/vendor/clipboard.min.js?1522185737` |
| +46 | @@\|\|pixhost.to/lang.js.php? | ++ | pixhost.to | 1 | script | `https://pixhost.to/lang.js.php?l=en&1522185737` |
| +46 | @@\|\|pixhost.to/js/helpers.js? | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/helpers.js?1522185737` |
| +46 | @@\|\|pixhost.to/js/main.js? | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/main.js?1522185737` |
| +46 |  |  | pixhost.to | 1 | image | `https://pixhost.to/image/flags/en.png` |
| +46 |  |  | pixhost.to | 1 | image | `https://pixhost.to/image/flags/ru.png` |
| +46 |  |  | pixhost.to | 1 | image | `https://pixhost.to/image/flags/de.png` |
| +46 |  |  | pixhost.to | 1 | image | `https://pixhost.to/image/flags/cz.png` |
| +46 |  |  | pixhost.to | 1 | image | `https://pixhost.to/image/flags/sk.png` |
| +46 |  |  | pixhost.to | 1 | image | `https://img44.pixhost.to/images/497/158604212_001-7.jpg` |
| +46 | \|\|exdynsrv.com^$3p | -- | pixhost.to | 3 | script | `https://a.exdynsrv.com/ads.js` |
| +46 |  |  | pixhost.to | 1 | image | `https://pixhost.to/image/logo_min.png?1522185737` |
| +46 | @@\|\|pixhost.to/js/vendor/jquery.*.js | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/vendor/jquery.cookie.js?1522185737` |
| +46 | @@\|\|pixhost.to/js/vendor/jquery-*.js? | ++ | pixhost.to | 1 | script | `https://pixhost.to/js/vendor/jquery-1.11.1.min.js?1522185737` |
| +46 |  |  | pixhost.to | 1 | css | `https://pixhost.to/css/main.css?1522185737` |
| +46 | ##+js(abort-on-property-write, readyADN) |  | pixhost.to |  | dom | `https://pixhost.to/show/497/158604212_001-7.jpg` |
| +46 | ##+js(abort-on-property-read, ShowIt) |  | pixhost.to |  | dom | `https://pixhost.to/show/497/158604212_001-7.jpg` |
| +46 | ##+js(abort-on-property-read, ExoDetector) |  | pixhost.to |  | dom | `https://pixhost.to/show/497/158604212_001-7.jpg` |
| +45 |  |  | pixhost.to | 1 | doc | `https://pixhost.to/show/497/158604212_001-7.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/489/158540689_01_hnbn_0.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/489/158540684_01.png` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/489/158540683_01.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/489/158540681_001.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/490/158542060_rj295099_img_main.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/490/158542058_rj270382_img_main.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/490/158543644_rj296894_img_main.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/492/158562092_gpn02_yariman_01.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/492/158562089_01_0.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/492/158562085_001.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/492/158565260_rj294401_img_main.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/494/158580861_001.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/494/158580863_001_vol111_01.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/494/158584661_rj296702_img_main.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/496/158595704_001-2.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/496/158595708_001.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/496/158595706_001-3.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/496/158595707_001-4.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/496/158598444_001.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/496/158598443_001-8.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/496/158598442_001-7.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/496/158598441_001-6.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/496/158598438_001-5.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/496/158598436_001-4.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/496/158598434_001-3.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/496/158598433_001-2.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/497/158604227_001.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/497/158604226_001-17.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/497/158604223_001-16.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/497/158604222_001-15.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/497/158604221_001-14.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/497/158604220_001-13.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/497/158604219_001-12.jpg` |
| +2 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/497/158604218_001-11.jpg` |
| +1 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/497/158604217_001-10.jpg` |
| +1 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/497/158604216_001-9.jpg` |
| +1 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/497/158604215_001-8.jpg` |
| +1 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/497/158604212_001-7.jpg` |
| +1 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/497/158604210_001-6.jpg` |
| +1 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/497/158604208_001-5.jpg` |
| +1 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/497/158604207_001-4.jpg` |
| +1 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/497/158604206_001-3.jpg` |
| +1 |  |  | cg-hentai.com | 3 | image | `https://t44.pixhost.to/thumbs/497/158604204_001-2.jpg` |
</details>

## External Info
- https://www.mypdns.org/T1103
- 
- 

### All Submissions:
- [X] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [X] Added a Screenshot for prove of Adult contents

### Todo
- [X] Added to [Source file](submit_here/strict_adult.txt)?
