### ISSUE TITLE
NSFW: snuff.tld

### ISSUE THREAD

**Issue by djdjnlaa** [Clefspeare13/pornhosts#194]
I believe this domain is an snuff(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python

www.
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [ ] Added ScreenDump for prove of False Positive

### Todo
- [ ] Added to [Source file](submit_here/hosts.txt)?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/wiki/RpzList#adult.mypdns.cloud) (@spirillen)

**Comment by spirillen** [comment]
spam
