### ISSUE TITLE
imagetwist.com

### ISSUE THREAD

**Issue by spirillen** [Clefspeare13/pornhosts#256]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
imagetwist.com
www.imagetwist.com
```

Please read `https://imagetwist.com/tos.html`

> All legal adult images are allowed.

## Content sources

(Please see #35)

```python
img33.imagetwist.com
img202.imagetwist.com
img300.imagetwist.com
```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/91854445-08fe7500-ec64-11ea-82df-03bbd8a8337e.png)

</details>

## Logger output
See <https://www.mypdns.org/T1282> for logger output

## External Info
- <https://www.mypdns.org/T1282>
- 
- 

### All Submissions:
- [X] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [X] Added a Screenshot for prove of Adult contents

### Todo
- [X] Added to [Source file](submit_here/hosts.txt)?
