### ISSUE TITLE
project1content.com

### ISSUE THREAD

**Issue by DaniV5** [Clefspeare13/pornhosts#264]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python

media-public-ht.project1content.com
prog-public-ec.project1content.com
site-api.project1service.com
images-assets-ht.project1content.com
```

## Content sources
i think these domains should be added to the list because it is used in brazzers.com
examples
https://media-public-ht.project1content.com/m=bIaldGO6Rr_d/420/7e1/801/261/49b/d90/b5f/67c/82d/ac3/f4/poster/poster_01.webp
https://media-public-ht.project1content.com/m=eyzaevFb/f58/c9f/eee/afb/42b/48f/8bf/d5b/435/eaa/6a/poster/poster_01.jpg
https://media-public-ht.project1content.com/m=eyzaevFb/46a/f10/8df/9ce/4ca/9af/bf0/391/f56/a1a/4c/poster/poster_01.jpg
(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

</details>

## External Info
- 
- 
- 

### All Submissions:
- [ ] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [ ] Added a Screenshot for prove of Adult contents

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [x] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
Yes these are CDN addresses used by brazzers and brazzersnetwork

**Comment by spirillen** [comment]
From <https://www.mypdns.org/T1308#16542>

```
static-ma-ht.project1content.com
```

**Comment by spirillen** [comment]
Closed by <https://github.com/Clefspeare13/pornhosts/commit/9a58dec3a1d17430a5f7c64a1727d579ba411f68>
