### ISSUE TITLE
various adult domains

### ISSUE THREAD

**Issue by KarelZe** [Clefspeare13/pornhosts#289]
I believe these domains are Adult(-related) domains, that should be added to host file

## Domains

```python
185.217.95.236
128.199.66.55
www.nudevista.at
www.pornktu.be
www.porn.biz
josspic.cam
www.sexvideosfree.cc
zphimsex.cc
www.freeones.ch
masaladesi.club
voyeur-house.club
bootyoftheday.co
perfektdamen.co
perfektdamen.co
m.perfektdamen.co
www.perfektdamen.co
www.adultwalls.com
www.alllesbiantube.com
www.amateurgirlsuk.com
www.asianpornmovies.com
www.aznude.com
www.babes.com
babesboobsbikinis.com
www.babestube.com
www.beegnow.com
www.bigporn.com
biqle.com
www.blendporn.com
www.boobcritic.com
www.boobpedia.com
boobyday.com
bunette.com
www.bunnylust.com
www.bustybloom.com
camwhoreshd.com
carlotta-champagne.com
www.centerfoldsblog.com
www.chatintime.com
www.cherrynudes.com
www.clips4sale.com
www.cloudygirls.com
comicxporn.com
coolchatfriends.com
www.live.czechsoles.com
www.desikahni.com
www.dirtynakedpics.com
www.dorcelclub.com
downblouseshots.com
www.drillmyhole.com
www.drpornofilme.com
www.dvderotik.com
www.eindeutscherporno.com
eispop.com
www.el-ladies.com
www.elitebabes.com
www.elktube.com
eugeniadiordiychuk.com
www.eugeniadiordiychuk.com
www.exgirlfriendmarket.com
www.eyny.com
fancentro.com
www.fapchat.com
de.faperoni.com
www.fastindianporn.com
freexxxhardcore.com
www.frischeporno.com
ftvmilfs.com
www.geheimelust.com
www.geilemaedchen.com
www.gifgoo.com
hdefporn.com
www.heavyonhotties.com
www.hernudepics.com
www.hierporno.com
www.home-made-videos.com
hotmaturewomensexcams.com
hotsislovesme.com
hqmaxporn.com
www.hulaporn.com
www.indiangaysite.com
tour.indianhiddencams.com
www.indianpornvideos2.com
indiansexuniversity.com
insidehim.com
www.itslive.com
javhoho.com
jizzbunker.com
jjgirls.com
www.kaamuu.com
www.kamababa.com
www.kingperv.com
kissjav.com
www.kittysplanet.com
www.legalporno.com
www.lesbianx.com
lustcore.com
lustcore.com
de.lxax.com
www.maturealbum.com
www.maturetube.com
www.melonstube.com
www.men.com
metart.com
www.metart.com
www.mobilepornmovies.com
mycum4k.com
www.mypornhere.com
mypornstarblogs.com
a.nips.com
noodlemagazine.com
www.novoglam.com
nudeamateurgalleries.com
nudogram.com
ooodesi.com
www.ozeex.com
www.pbabes.com
www.peeperz.com
www.people-69.com
de.pictoa.com
www.pipeporntube.com
www.playboyplus.com
www.playboytv.com
www.playvids.com
pmatehunter.com
de.porndoe.com
porndoo.com
www.pornflip.com
pornmaturetube.com
www.pornoaffe.com
www.pornoanimexxx.com
www.pornofeuer.com
www.pornoheit.com
www.pornoklaue.com
pornone.com
www.pornotom.com
pornounas.com
www.pornship.com
www.porntube247.com
porntubemaid.com
www.pornzog.com
www.porzo.com
pvrmall.com
screenhumor.com
www.seancody.com
sexier.com
sexodi.com
www.sexy-youtubers.com
sexycandidgirls.com
www.silkengirl.com
www.softnudecurves.com
www.spicybigtits.com
stripblackjackgames.com
syberpussy.com
syberpussy.com
tabooporns.com
www.teenones.com
www.teenqueenarchive.com
www.teensofindia.com
thecandidbay.com
topthaiporn.com
tourofbooty.com
www.tube3.com
www.uxdoll.com
videoporno5k.com
videosexabg.com
vipwank.com
www.vixenangels.com
www.voyeurstyle.com
vrconk.com
vrpornjack.com
www.wehateporn.com
www.whynotbi.com
www.xhamster-sexvideos.com
xjaps.com
xngay.com
xnostars.com
www.xnxx-pornos.com
xossipfap.com
www.xozilla.com
www.xtits.com
xxxvidso.com
www.yagyed.com
www.youpeg.com
zeenite.com
www.playboy.de
sexxhd.de
www.top5ficktreffen.de
www.tube8.es
www.xnxx.es
biguz.in
4ksex.me
www.redwap.me
xbay.me
2beeg.mobi
liebelib.mobi
xxnx.mobi
www.adultjoy.net
www.bestpornreviews.net
biguz.net
da.biguz.net
hu.biguz.net
ar.biguz.net
be.biguz.net
bg.biguz.net
bs.biguz.net
ca.biguz.net
cs.biguz.net
de.biguz.net
el.biguz.net
espanol.biguz.net
et.biguz.net
fi.biguz.net
fr.biguz.net
he.biguz.net
hr.biguz.net
hy.biguz.net
id.biguz.net
is.biguz.net
ja.biguz.net
ka.biguz.net
kk.biguz.net
ko.biguz.net
lt.biguz.net
lt.biguz.net
lv.biguz.net
mk.biguz.net
ms.biguz.net
mt.biguz.net
nl.biguz.net
no.biguz.net
pl.biguz.net
pt.biguz.net
ro.biguz.net
rus.biguz.net
sq.biguz.net
sr.biguz.net
sv.biguz.net
th.biguz.net
tr.biguz.net
uk.biguz.net
vi.biguz.net
zh.biguz.net
en.bysex.net
domporn.net
foxporns.net
fuckass.net
www.fullxxxvideos.net
www.hdpornos.net
hotmovs.net
incestvideo.net
josex.net
www.livejasminbabes.net
p720.net
www.paysitesreviews.net
www.playindianporn.net
www.pornohirsch.net
r34porn.net
www.sexei.net
www.striptube.net
www.sxyprn.net
xxxdownload.net
xxxstyanulo.net
www.mature.nl
seksmet.nl
de.xhamster.one
es.xhamster.one
fr.xhamster.one
artasian.online
www.private-nacktfotos.online
bangx.org
www.freexxxporn.org
upcomics.org
beeg.porn
www.spankbang.porn
sexvedio.pro
xnxx.realty
www.nakedcelebrities.site
famoussingers.top
fotoscaseras.top
hellopussy.top
www.teenfiles.top
teenstream.top
youngteens.top
bravotube.tv
www.pornoente.tv
www.tabooporn.tv
www.likuoo.video
siska.video
tour.desipapa.vip
free1s.world
www.imageweb.ws
www.coupons.xxx
fuck-videos.xxx
hdpornfree.xxx
www.pornhdvideos.xxx
sss.xxx
tabootube.xxx
vercomicsporno.xxx
www.xart.xxx
kittyhub.xyz
loliteen.xyz
```

## Content sources
- Mindgeeks Wikipedia article listing [its ventures](https://en.wikipedia.org/wiki/MindGeek)
- Various aggregator lists such as [this one](http://thesexlist.com) or [this one](www.lindylist.org) 
- Bing Search API

## External sources (reference)
not provided.

## Screenshots
not provided.

## Logger output
not provided.

## External Info
not provided.

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [ ] Added a Screenshot for prove of Adult contents

### Todo
- [ ] Added to [Source file](submit_here/hosts.txt)?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
Nice catch, but I've found at least 2 issues on your list :unamused: 

```python
185.217.95.236
128.199.66.55
```

You can't blacklist IP's through a hosts file driven project, but you can however contribute them to my [Porn Domain](https://www.mypdns.org/source/PornDomains/) (just notices that it should be rename :thinking:

**Comment by KarelZe** [comment]
Thanks @spirillen. How should we proceed then? Should I contribute those two ip adresses to your list and you or @Clefspeare13 will add the remaining entries to the host file?

Do you require screenshots for bulk submissions? 🤔

**Comment by spirillen** [comment]
> Thanks @spirillen. How should we proceed then? Should I contribute those two ip adresses to your list and you or @Clefspeare13 will add the remaining entries to the host file?
> 
> Do you require screenshots for bulk submissions? thinking

Hey @KarelZe 

1. By submitting the IP to my project they will be added to the RPZ zone for blocking and will requires users obtain them either through `adult.mypdns.cloud` RPZ zone or from the list in the repo (firewalls). Of curse you are welcome to contribute them :smiley: 
2. There two ways to get these issues (domains/IPs) into the list
  1. One domain(IP) = one issue/PR with screenshot (I will prefer issue do to my script and it's easier for commenting by other)
  2. Leave the list as bulk and wait for @Clefspeare13 to come around....

The reason I'm picky about it is, a good list have reasons for **why** and documentation, and are open for argumentation.

The other thing is, I'm the friendly neighborhood spider with these adult related lists, personally i have no issues with the subject, but I accept that some people might have, do to personal reasons **or** it just got to much some places, this leaving it a low priority to me vs my anti-tracking (privacy) project and @funilrys's https://github.com/funilrys/pyfunceble and that's makes it impossible for me to visit every single domain coming from bulk list to determine which is correct and which isn't, there a good screenshot says it all.

And I'll say the same to you as I do to everyone else, all "correctly" filed issues will end up in 3(4) different projects when i submit them by my scripts (it's yet private do to API-keys to various servers), so whether you issue the domains here at https://github.com/Clefspeare13/pornhosts or to mypdns.org (issues) (git https://github.com/mypdns/porn-domains) is the same for me :smiley: But IP can only go to the last mentioned :smirk: 

PS: Very nice detailed catch of `biguz.net` let's see more of that kind :smiling_imp:

**Comment by KarelZe** [comment]
Thanks @spirillen. I'll create an issue for the IPs at https://github.com/mypdns/porn-domains in the next days and wait for the other domains to be added by @Clefspeare13.

**Comment by spirillen** [comment]
I Have removed the following from your list, as I have created a issue for each of the following

```python
185.217.95.236
128.199.66.55
www.babes.com
metart.com
www.metart.com
www.playboytv.com
biguz.net
da.biguz.net
hu.biguz.net
ar.biguz.net
be.biguz.net
bg.biguz.net
bs.biguz.net
ca.biguz.net
cs.biguz.net
de.biguz.net
el.biguz.net
espanol.biguz.net
et.biguz.net
fi.biguz.net
fr.biguz.net
he.biguz.net
hr.biguz.net
hy.biguz.net
id.biguz.net
is.biguz.net
ja.biguz.net
ka.biguz.net
kk.biguz.net
ko.biguz.net
lt.biguz.net
lt.biguz.net
lv.biguz.net
mk.biguz.net
ms.biguz.net
mt.biguz.net
nl.biguz.net
no.biguz.net
pl.biguz.net
pt.biguz.net
ro.biguz.net
rus.biguz.net
sq.biguz.net
sr.biguz.net
sv.biguz.net
th.biguz.net
tr.biguz.net
uk.biguz.net
vi.biguz.net
zh.biguz.net
de.xhamster.one
es.xhamster.one
fr.xhamster.one
```
