### ISSUE TITLE
sexart.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#335]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
sexart.com
www.sexart.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-232815](https://user-images.githubusercontent.com/38778536/95655089-a779d200-0b50-11eb-88e3-5c86edf9389c.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [ ] Added to [Source file](submit_here/hosts.txt)?
- [x] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
Allready added

```shell
git blame submit_here/hosts.txt | grep sexart.com
Blaming lines: 100% (10477/10477), done.
d91e2d55 (Spirillen 2020-08-04 10:42:23 +0200   133) access.sexart.com
d91e2d55 (Spirillen 2020-08-04 10:42:23 +0200  2554) fhg.sexart.com
42b7c5f1 (Spirillen 2020-10-05 16:25:03 +0200  3263) members.sexart.com
d91e2d55 (Spirillen 2020-08-04 10:42:23 +0200  8713) www.sexart.com
```

See also https://www.mypdns.org/T1505
