### ISSUE TITLE
Additional adult content (TIP: sorry, i can't provide any screenshots or sources for a good reasons....)

### ISSUE THREAD

**Issue by Zorono** [Clefspeare13/pornhosts#339]
I believe this domain is an Adult(-related) domain --> that has to be blocked as..

## Domains
Only add the needed one See also #12

```python
fakecop.com
fakehospital.com
faketaxi.com
xnxxnetwork.com
xnxxvideos.net
xnxx-deutsch.com
xnxxteens.com
sexlog.com
sexy-youtubers.com
sexyjobs.com
sexedtalk.com
sisloveme.com
sexybabegirls.com
ftvmagic.com
videocelebs.net
videocelebs.com
oboobs.ru
```

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [ ] Added a Screenshot for prove of Adult contents

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [x] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
`fakecop.com` => <https://www.mypdns.org/T2158>
`fakehospital.com` => <https://www.mypdns.org/T2159>
`faketaxi.com` => <https://www.mypdns.org/T2160>
`xnxxnetwork.com` => <https://www.mypdns.org/T2161>
`xnxxvideos.net` => <https://www.mypdns.org/T2162>
`xnxx-deutsch.com` => <https://www.mypdns.org/T2163>
`xnxxteens.com` => <https://www.mypdns.org/T2164>
`sexlog.com` => <https://www.mypdns.org/T2165>
`sexy-youtubers.com` redirects to => `socialmediagirls.com` => <https://www.mypdns.org/T2166> Unless other proofs will be provided it won't be added
`sexyjobs.com` => <https://www.mypdns.org/T2167>
`sexedtalk.com` => <https://www.mypdns.org/T2168>
`sisloveme.com` => <https://www.mypdns.org/search/query/8bAa9.SV3c1n/#R>
`sexybabegirls.com` => <https://www.mypdns.org/search/query/sAmyQrJyNJMK/#R>
`ftvmagic.com` => <https://www.mypdns.org/search/query/TrQgqs3JrCWA/#R>
`videocelebs.com` => <https://www.mypdns.org/search/query/hFvjimxNr7Wv/#R>  redirects to => 
`videocelebs.net` => <https://www.mypdns.org/T2174>, Unless other proofs will be provided it won't be added
`oboobs.ru` => <https://www.mypdns.org/search/query/ND6yQqZqHi6e/#R>

**Comment by Zorono** [comment]
really i didn't understand anything since all of your provided links didn't authorize me to access what ever it do...
![image](https://user-images.githubusercontent.com/19735243/96884393-c0a04e00-1481-11eb-8639-10882087145e.png)

**Comment by spirillen** [comment]
> really i didn't understand anything since your provided links didn't authorize me to access what ever it do...
> ![image](https://user-images.githubusercontent.com/19735243/96884393-c0a04e00-1481-11eb-8639-10882087145e.png)

Yes, they are hidden, for not spreading the contents of Adult and adult-related contents, but just use your GH account to sigup and then sign <https://www.mypdns.org/L5> if you can :+1: then you can see the adult issues
