### ISSUE TITLE
COMODO Firewall

### ISSUE THREAD

**Issue by markangus2b** [Clefspeare13/pornhosts#343]
I believe this specific domain(s) is to be moved from the hosts file as it no longer is active for Adult material

# Delete this
```
personalfirewall.comodo.com
```

# Keep this
```
N/A
```

## Screenshots

<details><Summary>Screenshot</summary>

</details>

### All Submissions:
- [ ] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [ ] Added ScreenDump for prove of False Positive

### Todo
- [ ] Removed this from [Source file](submit_here/hosts.txt)?
- [ ] Removed from the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/wiki/RpzList#adult.mypdns.cloud) (@spirillen)

**Comment by spirillen** [comment]
Eh ok, comodo in an adult list :unamused: 

I'll fix it later, right now my systems are busy :zzz: :sleeping: 

```
grep -ri 'comodo.com' tmp/ source/ ../clefspeare13/pornhosts/submit_here/ ../Import-External-Sources/pornhosts/submit_here/ ../mypdns/porn-records/submit_here/
tmp/rpz.missing.bak:personalfirewall.comodo.com
tmp/rpz.missing:personalfirewall.comodo.com
../clefspeare13/pornhosts/submit_here/hosts.txt:personalfirewall.comodo.com
../Import-External-Sources/pornhosts/submit_here/hosts.txt:personalfirewall.comodo.com
../mypdns/porn-records/submit_here/adult.mypdns.cloud/hosts.list:personalfirewall.comodo.com
../mypdns/porn-records/submit_here/adult.mypdns.cloud/domains.list:personalfirewall.comodo.com
```

On the other hand, it proves why you never should trust a thirtparty blindly :smirk:
