### ISSUE TITLE
img1.wsimg.com

### ISSUE THREAD

**Issue by Cybo1927** [Clefspeare13/pornhosts#347]
I believe this specific domain(s) is to be moved from the hosts file as it no longer is active for Adult material

# Delete this
```
img1.wsimg.com
```

## Screenshots

<details><Summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/39284087/106395675-707b4500-63fb-11eb-9cb3-fac6318d7329.png)

</details>

## External Info

`https://github.com/nextdns/metadata/issues/525`

### All Submissions:
- [ ] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [ ] Added ScreenDump for prove of False Positive

### Todo
- [x] Removed this from [Source file](submit_here/hosts.txt)?
- [x] Removed from the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/wiki/RpzList#adult.mypdns.cloud) (@spirillen)

**Comment by spirillen** [comment]
- [ ] Build new hosts files
