### ISSUE TITLE
remove codecguide.com site 

### ISSUE THREAD

**Issue by lucknaumann** [Clefspeare13/pornhosts#351]
I believe this specific domain is to be moved from the hosts file as it is not Adult material. I have downloaded the K-Lite Codec Pack for years from there. For some reason it's on the list twice. Steven Black contributor dnmTX sent me here from [here](https://github.com/StevenBlack/hosts/issues/1607#issuecomment-817261402). Thanks.

# Delete this
```
codecguide.com
```

# Keep this
```
example..com
alive.example..com
```

## Screenshots

<details><Summary>Screenshot</summary>

</details>

### All Submissions:
- [ ] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [ ] Added ScreenDump for prove of False Positive

### Todo
- [x] Removed this from [Source file](submit_here/hosts.txt)?
- [ ] Removed from the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/wiki/RpzList#adult.mypdns.cloud) (@spirillen)

**Comment by lucknaumann** [comment]
Thanks! I presume this issue will close once the commit is merged?

**Comment by spirillen** [comment]
Yep, but as information to everyone, I can't generate the test/generation of a new good list until mid May, But you are welcome to do a manual removal from all lists within the https://github.com/Clefspeare13/pornhosts/tree/master/download_here and make it a PR, I will merge it asap.
