### ISSUE TITLE
spnati.net

### ISSUE THREAD

**Issue by arnoldsecret** [Clefspeare13/pornhosts#368]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
```
https://spnati.net/
https://www.spnati.net/
https://faraway-vision.io/
https://www.faraway-vision.io/
https://spnati.faraway-vision.io/
```
## Content sources
```
polyfill.io
```
## External sources (reference)
```
http://gitgud.io/spnati/spnati
```
## External Info
- 5-card strip poker game with community-made characters based on fictional works with a few original characters thrown in.

## Screenshots

<details><Summary>Screenshot required</summary>
Tried capturing, unfortunately I'm currently having a "Something went wrong" error while trying to upload the image.

</details>

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [ ] Added a Screenshot for prove of Adult contents

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [x] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
Added, issue will be closed when new lists is published
