### ISSUE TITLE
javhd.pics

### ISSUE THREAD

**Issue by spirillen** [Clefspeare13/pornhosts#63]
## Summary

I believe this domain is an Adult(-related) domain --> that have to 
be blocked as..

- [X] [Wildcarded](source/porno-sites/wildcard.list)
- [ ] [Single domain blocking](source/porno-sites/domains.list)

```python
javhd.pics   CNAME . ; Adult
*.javhd.pics   CNAME . ; Adult
```

### additional for hosts
```shell

www.
```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/72481706-a99a4480-37fb-11ea-974f-b8840633a7a1.png)

</details>

### All Submissions:
- [x] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [x] Added ScreenDump for prove of False Positive

### Todo
- [ ] Added to Source file?

#### See also:
- https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1766
- https://github.com/mypdns/matrix/issues/38
- https://github.com/Import-External-Sources/pornhosts/issues/83
- http://wiki.mypdns.org/ticket/123
