### ISSUE TITLE
pornhat.com

### ISSUE THREAD

**Issue by spirillen** [Clefspeare13/pornhosts#64]
## Summary

I believe this domain is an Adult(-related) domain --> that have to 
be blocked as..

- [X] [Wildcarded](source/porno-sites/wildcard.list)
- [ ] [Single domain blocking](source/porno-sites/domains.list)

```python
pornhat.com   CNAME . ; Adult
*.pornhat.com   CNAME . ; Adult
```

### additional for hosts
```shell
static.pornhat.com
vr.pornhat.com
www.pornhat.com
```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/72674078-f3d92b00-3a72-11ea-8534-a7704b1202c6.png)

</details>

### All Submissions:
- [x] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added ScreenDump for prove of False Positive

### Todo
- [ ] Added to Source file?

#### See also:
- https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1770
- https://github.com/Import-External-Sources/pornhosts/issues/84
