### ISSUE TITLE
pornhat.net

### ISSUE THREAD

**Issue by spirillen** [Clefspeare13/pornhosts#65]
## Summary

I believe this domain is an Adult(-related) domain --> that have to 
be blocked as..

- [X] [Wildcarded](source/porno-sites/wildcard.list)
- [ ] [Single domain blocking](source/porno-sites/domains.list)

```python
pornhat.net   CNAME . ; Adult
*.pornhat.net   CNAME . ; Adult
```

### additional for hosts
```shell

www.
```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](/uploads/75347c5de85dda0079c8664e5ec203ef/image.png)

</details>

### All Submissions:
- [x] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added ScreenDump for prove of False Positive

### Todo
- [ ] Added to Source file?

#### See also:
- https://github.com/easylist/easylist/pull/4279
- https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1771
- https://github.com/Import-External-Sources/pornhosts/issues/85
- https://www.mypdns.org/ticket/126
