### ISSUE TITLE
hentaibeast.com

### ISSUE THREAD

**Issue by spirillen** [Clefspeare13/pornhosts#67]
I believe this domain is an Adult(-related) domain --> that have to 
be blocked as..

```python
hentaibeast.com
www.hentaibeast.com
```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/72676039-e2048180-3a8c-11ea-9223-1fed8298a177.png)

</details>

## External Info

- https://github.com/Sinfonietta/hostfiles/issues/80
- https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1773
- https://gitlab.com/my-privacy-dns/matrix/matrix/commit/33f98952c0a588fc5c3945c905ccb5884b99e925
- https://github.com/Import-External-Sources/pornhosts/issues/87

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Positive

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?

**Comment by spirillen** [comment]
![image](https://user-images.githubusercontent.com/44526987/79705633-a741fd80-82b6-11ea-98a9-9ad94f79c563.png)

![image](https://user-images.githubusercontent.com/44526987/79705656-b45eec80-82b6-11ea-9f0b-75555fcccb58.png)
