### ISSUE TITLE
hcomicbook.com

### ISSUE THREAD

**Issue by spirillen** [Clefspeare13/pornhosts#68]
I believe this domain is an Adult(-related) domain --> that have to 
be blocked as..

```python
hcomicbook.com
www.hcomicbook.com
```

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +5 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/favicon.ico` |
| +2 | ##.addthis_toolbox |  | hcomicbook.com |  | dom | `http://hcomicbook.com/` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/western-thumb159x230/9/0000009559/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/western-thumb159x230/0/0000000295/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/western-thumb159x230/8/0000008981/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/western-thumb159x230/8/0000008853/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/western-thumb159x230/7/0000007719/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/western-thumb159x230/6/0000006581/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/western-thumb159x230/6/0000006024/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/western-thumb159x230/6/0000006264/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/western-thumb159x230/42/0000042580/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/western-thumb159x230/6/0000006609/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/western-thumb159x230/9/0000009932/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/western-thumb159x230/0/0000000369/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/manga-thumb159x230/51/0000051879/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/manga-thumb159x230/49/0000049796/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/manga-thumb159x230/22/0000022097/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/manga-thumb159x230/7/0000007073/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/manga-thumb159x230/11/0000011162/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/manga-thumb159x230/13/0000013446/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/manga-thumb159x230/18/0000018582/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/manga-thumb159x230/12/0000012979/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/manga-thumb159x230/19/0000019900/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/manga-thumb159x230/54/0000054065/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/manga-thumb159x230/4/0000004296/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/manga-thumb159x230/19/0000019073/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/doujin-thumb159x230/35/0000035976/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/doujin-thumb159x230/41/0000041421/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/doujin-thumb159x230/0/0000000260/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/doujin-thumb159x230/72/0000072261/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/doujin-thumb159x230/18/0000018138/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/doujin-thumb159x230/63/0000063047/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/doujin-thumb159x230/29/0000029425/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/doujin-thumb159x230/54/0000054453/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/doujin-thumb159x230/35/0000035960/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/doujin-thumb159x230/21/0000021754/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/doujin-thumb159x230/18/0000018396/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/doujin-thumb159x230/40/0000040809/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://www.hcomicbook.com/imglink/doujin-thumb159x230/21/0000021694/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://www.hcomicbook.com/imglink/doujin-thumb159x230/3/0000003621/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://hcomicbook.com/imglink/doujin-thumb159x230/5/0000005742/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | image | `http://www.hcomicbook.com/imglink/doujin-thumb159x230/6/0000006508/001.jpg` |
| +1 |  |  | hcomicbook.com | 1 | css | `http://hcomicbook.com/static/css/style.css` |
| +0 |  |  | hcomicbook.com | 1 | doc | `http://hcomicbook.com/` |
</details>

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/72676381-f64a7d80-3a90-11ea-9da8-3555f1fe2172.png)

</details>

## External Info

- https://github.com/Sinfonietta/hostfiles/issues/80
- https://www.mypdns.org/ticket/129
- https://github.com/mypdns/matrix/issues/42

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Positive

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?

**Comment by spirillen** [comment]
`hcomicbook.com` have become unresponsive, so only adding `www.hcomicbook.com`
