### ISSUE TITLE
ibsearch.xxx

### ISSUE THREAD

**Issue by spirillen** [Clefspeare13/pornhosts#69]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

```python
ibsearch.xxx
im1.ibsearch.xxx
```
For details about this domain, we need a third party information from <https://github.com/austinhuang0131/node-ibsearch>
This explain why it is difficult to find the prof.

## Screenshots

<details><Summary>Screenshot required</summary>

https://im1.ibsearch.xxx/f/10/8fd9c0647a88d349a0b34295c7e41.jpg

</details>

## External Info
- https://github.com/Sinfonietta/hostfiles/issues/80
- https://www.mypdns.org/ticket/130
- https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1775
- https://github.com/Import-External-Sources/pornhosts/issues/90

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [X] Added ScreenDump for prove of False Positive

### Todo
- [ ] Added to [Source file](submit_here/hosts.txt)?
