### ISSUE TITLE
sxshentai.com

### ISSUE THREAD

**Issue by spirillen** [Clefspeare13/pornhosts#70]
I believe this domain is an Adult(-related) domain --> that have to 
be blocked as..

```python
sxshentai.com
www.sxshentai.com redirects to sxshentai.com
```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/72676958-60662100-3a97-11ea-9386-dca9491d4e63.png)

</details>

## External Info
- https://github.com/Sinfonietta/hostfiles/issues/80
- https://www.mypdns.org/ticket/130
- https://github.com/Import-External-Sources/pornhosts/issues/91
- https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1776

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Positive

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
