### ISSUE TITLE
037jav.com

### ISSUE THREAD

**Issue by spirillen** [Clefspeare13/pornhosts#94]
I believe this specific domain(s) is to be moved from the hosts file as it no longer is active for Adult material

# Delete this
```
037jav.com
```
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +3 | \|\|google.*^ | -- | ww1.037jav.com | 3 | script | `http://www.google.com/adsense/domains/caf.js` |
| +3 | \|\|sedoparking.com^ | -- | ww1.037jav.com | 3 | script | `http://img.sedoparking.com/js/jquery-1.11.3.custom.min.js` |
| +3 |  |  | behind-the-scene | 0,3 | xhr | `https://255.255.255.255/moz-extension://53cfdd28-130e-46ec-8607-995049ad51d9/?id=70792b77fe.01ec%2Chttp%3A%2F%2Fww1.037jav.com%2F%3Fsub1%3D7ae284b0-8e20-11ea-9eb2-b71e214398df&url=http%3A%2F%2Fww1.037jav.com%2F%3Fsub1%3D7ae284b0-8e20-11ea-9eb2-b71e214398df&top=true&suspend=true` |
| +3 | \|\|sedoparking.com^ | -- | ww1.037jav.com | 3 | script | `http://img.sedoparking.com/js/jquery-1.11.3.custom.min.js` |
| +3 | no-remote-fonts: * true | -- | ww1.037jav.com | 1 | inline-font | `http://ww1.037jav.com/?sub1=7ae284b0-8e20-11ea-9eb2-b71e214398df` |
| +2 |  |  | ww1.037jav.com | 1 | doc | `http://ww1.037jav.com/?sub1=7ae284b0-8e20-11ea-9eb2-b71e214398df` |
| +2 | no-remote-fonts: * true | -- | 037jav.com | 1 | inline-font | `http://037jav.com/?js=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJKb2tlbiIsImV4cCI6MTU4ODYxNTI3NCwiaWF0IjoxNTg4NjA4MDc0LCJpc3MiOiJKb2tlbiIsImpzIjoxLCJqdGkiOiIybzV0dDgzMnU0cHI5MmxxaGMwOGx1bWEiLCJuYmYiOjE1ODg2MDgwNzQsInRzIjoxNTg4NjA4MDc0MDE0MjE0fQ.gpaaTPbw9cmiswX5W-0Zm89yJYRKWc8YYPBtwdmtuEY&sid=7ae284b0-8e20-11ea-9eb2-b71e214398df` |
| +1 |  |  | 037jav.com | 1 | doc | `http://037jav.com/?js=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJKb2tlbiIsImV4cCI6MTU4ODYxNTI3NCwiaWF0IjoxNTg4NjA4MDc0LCJpc3MiOiJKb2tlbiIsImpzIjoxLCJqdGkiOiIybzV0dDgzMnU0cHI5MmxxaGMwOGx1bWEiLCJuYmYiOjE1ODg2MDgwNzQsInRzIjoxNTg4NjA4MDc0MDE0MjE0fQ.gpaaTPbw9cmiswX5W-0Zm89yJYRKWc8YYPBtwdmtuEY&sid=7ae284b0-8e20-11ea-9eb2-b71e214398df` |
| +1 |  |  | behind-the-scene | 0,3 | xhr | `https://255.255.255.255/moz-extension://53cfdd28-130e-46ec-8607-995049ad51d9/?id=50a2bf1233.2d98%2Chttp%3A%2F%2F037jav.com%2F&url=http%3A%2F%2F037jav.com%2F&top=true&suspend=true` |
| +1 | no-remote-fonts: * true | -- | 037jav.com | 1 | inline-font | `http://037jav.com/` |
| +0 |  |  | 037jav.com | 1 | doc | `http://037jav.com/` |
</details>

## Screenshots

<details><Summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/44526987/80986809-5e02b980-8e31-11ea-8f04-93161a859108.png)

</details>

## External Info
- https://github.com/Import-External-Sources/pornhosts/issues/634

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [X] Added ScreenDump for prove of False Positive

### Todo
- [ ] Removed this from [Source file](submit_here/hosts.txt)?
