### ISSUE TITLE
0i0i0i0.com

### ISSUE THREAD

**Issue by spirillen** [Clefspeare13/pornhosts#96]
I believe this specific domain(s) is to be moved from the hosts file as it no longer is active for Adult material

# Delete this
```
0i0i0i0.com
```

## Screenshots

<details><Summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/44526987/80989258-f9e1f480-8e34-11ea-84ef-b784f5f7e513.png)

</details>

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/rtb/logo/47/download.jfif` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/29/tubecorporate_H__2x_2x.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/28/trafficshop_H__2x_2x.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/33/trafficstars.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/27/traffichunt.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/26/trafichaus__2x_2x_2.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/25/trafficforce__V__2x_2x.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/rtb/logo/68/logo.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/rtb/logo/115/1_fISNcJ7o1RHzXmfcXS7MJA.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/22/royalads.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/83/rivertraffic.com_logo_bg_white__.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/2/propeller__H__2x_2x.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/80/popmyads.com_logo_bg_transp__.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/20/popcash-2x__2x_2x.png` |
| +1365 | /popads_ | -- | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/1/popads_logo_H__2x_2x.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/19/plugrush.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/rtb/logo/109/plio.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/rtb/logo/104/mbc.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/rtb/logo/89/logo_mojoo.JPG` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/17/juicy.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/75/inxyads.com_logo_bg_transp__.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/rtb/logo/90/ibizadspink.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/16/hilltopads.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/rtb/logo/102/heartbid.JPG` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/rtb/logo/72/gadsbee_logo__.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/15/fpc.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/rtb/logo/105/explorads_logo_new.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/14/exo.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/rtb/logo/110/0f78f8c9408e15b267ac4.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/12/twinred.jpg` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/32/clickaine_logo_H__2x_2x.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/10/clickadu.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/rtb/logo/103/bp.JPG` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/99/IMG_20200128_112749_418.jpg` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/rtb/logo/64/af.JPG` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/rtb/logo/86/Adt_logo_500x500px-01.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/7/adsupply.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/6/adsterra_H__2x_2x_w180.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/76/adskeeper.com_logo__.png` |
| +1365 |  |  | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/5/Adnium__2x_2x.png` |
| +1365 | /adcash.$domain=~adcash.com | -- | `www.adspyglass.com` | 1 | image | `https://www.adspyglass.com/uploads/source_info/common/logo/4/adcash.png` |
| +1363 |  |  | `www.adspyglass.com` | 1 | xhr | `https://app.adspyglass.com/landing/brokers.json` |
| +1363 |  |  | `www.adspyglass.com` | 1 | xhr | `https://app.adspyglass.com/users/current.json` |
| +1361 |  |  | `www.adspyglass.com` | 3 | script | `https://cdn.asgcdn.com/landing.js` |
| +1356 | `##[href^="https://www.facebook.com"]` |  | `www.adspyglass.com` |  | dom | `https://www.adspyglass.com/welcome?utm_source=aabdomains&utm_medium=0i0i0i0.com` |
| +1356 | `##[href^="https://twitter.com"]` |  | `www.adspyglass.com` |  | dom | `https://www.adspyglass.com/welcome?utm_source=aabdomains&utm_medium=0i0i0i0.com` |
| +1356 | ##.youtube-icon |  | `www.adspyglass.com` |  | dom | `https://www.adspyglass.com/welcome?utm_source=aabdomains&utm_medium=0i0i0i0.com` |
| +1356 | ##.socicon |  | `www.adspyglass.com` |  | dom | `https://www.adspyglass.com/welcome?utm_source=aabdomains&utm_medium=0i0i0i0.com` |
| +1356 | ##.cookies-block |  | `www.adspyglass.com` |  | dom | `https://www.adspyglass.com/welcome?utm_source=aabdomains&utm_medium=0i0i0i0.com` |
| +1356 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e3bda478c10fb81e0d642b2_favicon-logo-32%20%2B.png` |
| +1356 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e3bda4b529ab113e96f68d7_favicon-logo-256%20%2B.png` |
| +1356 | google-analytics.com/analytics.js | << | `www.adspyglass.com` |  | script | `https://www.google-analytics.com/analytics.js` |
| +1356 | \|\|google-analytics.com^ | -- | `www.adspyglass.com` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +1355 | no-remote-fonts: * true | -- | `www.adspyglass.com` | 3 | font | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e2f24f0842db36ea0deb372_lato-700-my.woff` |
| +1355 | no-remote-fonts: * true | -- | `www.adspyglass.com` | 3 | font | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e2f550281bcaa8c76be078f_roboto-cond-700-my.woff` |
| +1355 | no-remote-fonts: * true | -- | `www.adspyglass.com` | 3 | font | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e2f5502c8eec2a191ab5bd1_roboto-cond-300-my.woff` |
| +1355 | no-remote-fonts: * true | -- | `www.adspyglass.com` | 3 | font | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e2ed378b0712412a2dd5a06_my-montserrat-v14-latin-500.woff` |
| +1355 | no-remote-fonts: * true | -- | `www.adspyglass.com` | 1 | inline-font | `https://www.adspyglass.com/welcome?utm_source=aabdomains&utm_medium=0i0i0i0.com` |
| +1355 | no-remote-fonts: * true | -- | `www.adspyglass.com` | 3 | font | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e2f550278b207f669bfa763_roboto-cond-400-my.woff` |
| +1355 | no-remote-fonts: * true | -- | `www.adspyglass.com` | 3 | font | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e2ed3785b8beddc3bbdda68_my-montserrat-v14-latin-900.woff` |
| +1355 | no-remote-fonts: * true | -- | `www.adspyglass.com` | 3 | font | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e2f24f0feb2b7c1376a897b_lato-700-my.woff2` |
| +1355 | no-remote-fonts: * true | -- | `www.adspyglass.com` | 3 | font | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e2f550294e2dbc24982bc17_roboto-cond-700-my.woff2` |
| +1355 | no-remote-fonts: * true | -- | `www.adspyglass.com` | 3 | font | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e2f55029cd3918f7551b8b9_roboto-cond-300-my.woff2` |
| +1355 | no-remote-fonts: * true | -- | `www.adspyglass.com` | 3 | font | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e2ed3782ca1f776491b426f_my-montserrat-v14-latin-500.woff2` |
| +1355 | no-remote-fonts: * true | -- | `www.adspyglass.com` | 3 | font | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e2f5502cb2e5ef831e0320d_roboto-cond-400-my.woff2` |
| +1355 | no-remote-fonts: * true | -- | `www.adspyglass.com` | 3 | font | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e2ed3782ca1f71fa61b4270_my-montserrat-v14-latin-900.woff2` |
| +1355 | _facebook- | -- | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5a85a92120c95100013efdbc_facebook-white.svg` |
| +1355 | _twitter-$image | -- | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5a85a92120c95100013efdaa_twitter-white.svg` |
| +1355 | \|\|facebook.net^$script | -- | `www.adspyglass.com` | 3 | script | `https://connect.facebook.net/en_US/fbevents.js` |
| +1355 | google-analytics.com/analytics.js | << | `www.adspyglass.com` |  | script | `https://www.google-analytics.com/analytics.js` |
| +1355 | \|\|google-analytics.com^ | -- | `www.adspyglass.com` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +1353 | \|\|googleapis.com^$important | -- | `www.adspyglass.com` | 3 | script | `https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js` |
| +1353 |  |  | `www.adspyglass.com` | 3 | script | `https://cdnjs.cloudflare.com/ajax/libs/lazysizes/3.0.0/lazysizes.min.js` |
| +1353 |  |  | `www.adspyglass.com` | 3 | css | `https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.6.2/css/bootstrap-slider.min.css` |
| +1353 |  |  | `www.adspyglass.com` | 3 | script | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/js/webflow.1b0b4f7f3.js` |
| +1353 |  |  | `www.adspyglass.com` | 3 | script | `https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.4.1.min.220afd743d.js?site=5a85a92120c95100013efd7f` |
| +1353 | _facebook- | -- | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5a85a92120c95100013efdbc_facebook-white.svg` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5a85a92120c95100013efd99_youtube-white.svg` |
| +1353 | _twitter-$image | -- | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5a85a92120c95100013efdaa_twitter-white.svg` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5c9bde804935ea3e22987d4d_AdSpyglass%20%D0%BB%D0%BE%D0%B3%D0%BE%20%D0%BD%D0%B0%20%D1%82%D0%B5%D0%BC%D0%BD%D0%BE%D0%BC.png` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e32ca993ab26b1688a3b328_5e324289338ff1e4ad9f2776_5db6cf4b83d31e7a435e28b6_13%20filter%20(1)%20(1).jpg` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e32ca80577bd4b90babbf34_5e324277012ef4095f75385e_5db6cf4d83d31ec7f35e28bf_14%20grouping%20(1)%20(1).jpg` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e32ca6cbd23a234b6a823c0_5e324263f2105941c994541d_5db6cf4dda94826deef028ba_screenshot%20-%20Report%20by%20day-p-1080%20(1)%20(1).jpeg` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e32ca403ab26b34bca3ad35_5e32424e012ef46234753817_5db6cf4d5e46c18c1679b9c3_screenshot%20-%20Report%20by%20income-p-1080%20(1)%20(1).jpeg` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e4abcc795e7fae0b3e19e15_Youtube%20cover.jpg` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5c90b730a5701d02f59e1163_013-chain%20red.svg` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5c90b7305e8ec19cb897ee15_010-passion%20red.svg` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5c90b5b45ef96fbc23b4d74a_001-share%20red.svg` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5c90b7ff70f1f442f0d0e5cf_017-file-1%20red%202.svg` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5c90b8796f6f88e7539d1e2c_005-multimedia%20red.svg` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e32ff1a3d7bc4003c9d61e9_Paypal%20logo%20H%20-%20232%20%2B.png` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5c8d1e282f2b678cedb9322a_paxum%20logo%20H.png` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e32ff09cb2c596f5731dfe2_WebMoney%20logo%20H%20-%20252%20%2B.png` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e32fff3cb2c5950a031e8f2_wire%20transfer%20bank%20bg%20transp%20hor%20200.png` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5dba5d0303e4c0753f4de76f_5d593c703f278981ea7f59f0_payoneer%20logo%20bg%20transp(1).png` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e3300df7063a307d1fd7e49_bitcoin%20logo%20H%20-%20230.png` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e2fcd1f01dafd037c6f6e7d_5c8d24024e2db83387af56a6_epayments%20logo%20H%20(1).png` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e440406b9e37bbccb0f977f_check%20-%20opt.png` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5db2c98de800a5dfc2f38e34_popmyads.com%20logo%20bg%20transp%20%2B%20(2).png` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5c92a7ebc0e6ab22ce5ba932_Clickadu%20logo%20for%20keyvisual.png` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5c92a7eafa85655ebe7aca33_Adsterra%20logo%20for%20keyvisual.png` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5c90d3de70f1f44f33d14591_trafficstars%20H%20%402x%402x.png` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5c9e3d19032049f0530fe908_propeller%20%20H%20%402x%20only%20logo.png` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5c92a7ebc62eaa8a409af966_PopAds%20logo%20for%20keyvisual.png` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5c90d3dc57008a25f140e165_adcash%20logo%20H%20%402x%402x.png` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5ca600c27e34be2315df2603_Adspyglass%20logo%20thin%202.svg` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5c9505a2c2075b6fcb1a046c_002-play-button%20blue-60pr.svg` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5c95060dc2075b70301a052c_002-play-button%20white.svg` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5e2fcd9c5251e138a423ff76_5daf4be14d7026322077f894_arrow%20black%2012x8%20(1).png` |
| +1353 |  |  | `www.adspyglass.com` | 3 | image | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/5c8c03cba49d4808cbd0b5da_AdSpyglass-logo.png` |
| +1353 |  |  | behind-the-scene | 0,3 | xhr | `https://255.255.255.255/moz-extension://53cfdd28-130e-46ec-8607-995049ad51d9/?id=4adb364ce8.92e%2Chttps%3A%2F%2Fwww.adspyglass.com%2Fwelcome%3Futm_source%3Daabdomains%26utm_medium%3D0i0i0i0.com&url=https%3A%2F%2Fwww.adspyglass.com%2Fwelcome%3Futm_source%3Daabdomains%26utm_medium%3D0i0i0i0.com&top=true&suspend=true` |
| +1353 | \|\|googleapis.com^$important | -- | `www.adspyglass.com` | 3 | script | `https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js` |
| +1353 |  |  | `www.adspyglass.com` | 3 | css | `https://uploads-ssl.webflow.com/5a85a92120c95100013efd7f/css/adspyglass.webflow.f8ebd2310.min.css` |
| +1353 | no-remote-fonts: * true | -- | `www.adspyglass.com` | 1 | inline-font | `https://www.adspyglass.com/welcome?utm_source=aabdomains&utm_medium=0i0i0i0.com` |
| +1351 |  |  | `www.adspyglass.com` | 1 | doc | `https://www.adspyglass.com/welcome?utm_source=aabdomains&utm_medium=0i0i0i0.com` |
| +1351 | no-remote-fonts: * true | -- | 0i0i0i0.com | 1 | inline-font | `http://0i0i0i0.com/` |
| +1350 |  |  | 0i0i0i0.com | 1 | doc | `http://0i0i0i0.com/` |
| +2 |  |  | behind-the-scene | 0,3 | xhr | `https://255.255.255.255/moz-extension://53cfdd28-130e-46ec-8607-995049ad51d9/?id=70792b77fe.01ec%2Chttp%3A%2F%2Fww1.037jav.com%2F%3Fsub1%3D7ae284b0-8e20-11ea-9eb2-b71e214398df&url=http%3A%2F%2Fww1.037jav.com%2F%3Fsub1%3D7ae284b0-8e20-11ea-9eb2-b71e214398df&top=true&suspend=true` |
| +0 |  |  | behind-the-scene | 0,3 | xhr | `https://255.255.255.255/moz-extension://53cfdd28-130e-46ec-8607-995049ad51d9/?id=50a2bf1233.2d98%2Chttp%3A%2F%2F037jav.com%2F&url=http%3A%2F%2F037jav.com%2F&top=true&suspend=true` |
</details>

## External Info
- https://www.mypdns.org/T655

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [X] Added ScreenDump for prove of False Positive

### Todo
- [ ] Removed this from [Source file](submit_here/hosts.txt)?

**Comment by spirillen** [comment]
Already fixed.... mistake in my internal file.... closing
